# FROM node:16-alpine as build

# WORKDIR /usr/src/app

# COPY --chown=node:node package*.json ./

# RUN rm -rf node_modules && yarn install --immutable --immutable-cache --check-cache

# COPY --chown=node:node . .

# RUN yarn build

# USER node

# FROM node:16-alpine AS deploy

# WORKDIR /usr/src/app

# COPY --chown=node:node  --from=build /usr/src/app/dist/ ./dist
# COPY --chown=node:node --from=build /usr/src/app/node_modules/ ./node_modules

# ENV NODE_ENV development

# EXPOSE 8081

# CMD [ "node", "dist/main.js" ]



FROM node:16-alpine AS base

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn --production

# install node-prune (https://github.com/tj/node-prune)
RUN apk add curl bash --no-cache && curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b /usr/local/bin

FROM base AS dev

# You MUST specify files/directories you don't want on your final image like .env file, dist, etc. The file .dockerignore at this folder is a good starting point.
COPY . .
RUN ls -l

# install required depedencies for compile related TypeScript/NestJS code
RUN yarn

# lint and formatting configs are commented out
# uncomment if you want to add them into the build process
# RUN yarn lint
RUN yarn build

# run node prune
RUN /usr/local/bin/node-prune

# use one of the smallest images possible
FROM node:16-alpine
# get package.json from base stage
COPY --from=base /usr/src/app/package.json ./
# get the dist back
COPY --from=dev /usr/src/app/dist/ ./dist/
# get the node_modules from base stage
COPY --from=base /usr/src/app/node_modules/ ./node_modules/
# expose application port 
EXPOSE 8081
# start
CMD ["node", "dist/main.js"]