FROM node:16-alpine AS base

RUN  apk add curl bash && curl -sfL https://gobinaries.com/tj/node-prune | bash -s -- -b /usr/local/bin

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN npm install -g rimraf

RUN yarn --production

FROM base AS dev

# You MUST specify files/directories you don't want on your final image like .env file, dist, etc. The file .dockerignore at this folder is a good starting point.
COPY . .
RUN ls -a

# install required depedencies for compile related TypeScript/NestJS code
RUN yarn

# lint and formatting configs are commented out
# uncomment if you want to add them into the build process
# RUN yarn lint
RUN yarn build

# run node prune
RUN /usr/local/bin/node-prune

# use one of the smallest images possible
FROM node:16-alpine
# get package.json from base stage
COPY --from=base /usr/src/app/package.json ./
# get the dist back
COPY --from=dev /usr/src/app/dist/ ./dist/
# get the node_modules from base stage
COPY --from=base /usr/src/app/node_modules/ ./node_modules/
# expose application port 
EXPOSE 8081
# start
CMD ["node", "dist/main.js"]