import { SIGNIN_DESCRIPTION } from './auth';
import {
  READ_PLANT_DETAIL,
  READ_PLANT_INFORMATION,
  READ_PLANT_WATER_LOG,
} from './plants';

export const ERROR_DESCRIPTION = {
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
};

export {
  SIGNIN_DESCRIPTION,
  READ_PLANT_DETAIL,
  READ_PLANT_INFORMATION,
  READ_PLANT_WATER_LOG,
};
