import { SIGNIN_DESCRIPTION } from './auth';
import {
  PLANT_INFORMATION,
  GET_PLANT_WATER_LOG,
  CREATE_PLANT_WATER,
} from './plants';

export const ERROR_DESCRIPTION = {
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
};

export {
  SIGNIN_DESCRIPTION,
  PLANT_INFORMATION,
  GET_PLANT_WATER_LOG,
  CREATE_PLANT_WATER,
};
